# Generated by Django 3.2.9 on 2021-12-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cuenta')),
            ],
        ),
    ]
