# Generated by Django 3.2.9 on 2021-12-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_filtromovimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtromovimientos',
            name='asiento',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='filtromovimientos',
            name='fecha_final',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='filtromovimientos',
            name='fecha_inicial',
            field=models.CharField(default='', max_length=10),
        ),
    ]
