# Generated by Django 3.2.9 on 2021-12-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211226_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=10)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
