# Generated by Django 3.2.10 on 2022-01-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211231_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.CharField(help_text='etiqueta', max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre para los informes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroInformes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.CharField(default='', max_length=10)),
                ('fecha_final', models.CharField(default='', max_length=10)),
                ('tipo', models.CharField(choices=[('diario', 'diario'), ('semanal', 'semanal'), ('mensual', 'mensual'), ('trimestral', 'trimestral'), ('anual', 'anual')], default='diario', max_length=10)),
                ('cuenta', models.CharField(default='', max_length=10)),
                ('etiqueta', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='filtrocuentas',
            name='etiqueta',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='filtromovimientos',
            name='etiqueta',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtrocuentas',
            name='campo',
            field=models.CharField(choices=[('num', 'num'), ('nombre', 'nombre'), ('etiqueta', 'etiqueta')], default='num', max_length=10),
        ),
        migrations.AlterField(
            model_name='filtromovimientos',
            name='campo',
            field=models.CharField(choices=[('num', 'num'), ('fecha', 'fecha'), ('descripcion', 'descripcion'), ('debe', 'debe'), ('haber', 'haber'), ('cuenta', 'cuenta')], default='num', max_length=15),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='etiqueta',
            field=models.ManyToManyField(help_text='Etiqueta o etiquetas para la generación de informes', to='main.Etiqueta'),
        ),
    ]
