# Generated by Django 3.2.10 on 2022-01-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220115_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiltroInformes',
        ),
    ]
